# .github/workflows/deploy.yml

name: Build on Cloud, Deploy on Raspberry Pi (Java 11)

on:
  push:
    branches:
      - main

jobs:
  # --- ЗАДАЧA №1: СБОРКА НА БЫСТРОМ СЕРВЕРЕ GITHUB ---
  build:
    runs-on: ubuntu-latest # Используем облачный runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-jar # Имя артефакта
          path: build/libs/*.jar

  # --- ЗАДАЧА №2: ДЕПЛОЙ НА RASPBERRY PI ---
  deploy:
    needs: build # Эта задача ждет завершения 'build'
    runs-on: self-hosted # А вот эта выполняется на вашем Pi

    steps:
      - name: Download JAR from build job
        uses: actions/download-artifact@v4
        with:
          name: bot-jar # Скачиваем артефакт с тем же именем

      - name: Deploy and restart bot service
        run: |
          JAR_NAME="this_is_kind_of_obed_bot-1.0-SNAPSHOT.jar"
          APP_DIR="/home/pi/Desktop/app"

          echo "Deploying new version..."
          # Перемещаем скачанный JAR в папку приложения
          mv $JAR_NAME "$APP_DIR/$JAR_NAME"
          
          echo "Restarting obed-bot service..."
          sudo systemctl restart obed-bot.service
          
          echo "Deployment finished!"