# .github/workflows/deploy.yml

name: Build on Cloud, Deploy on Raspberry Pi (Java 11)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Меняем v4 на v3
      - name: Checkout code
        uses: actions/checkout@v3 # <--- ИЗМЕНЕНИЕ

      # Для setup-java v4 пока совместим, но для надежности можно и его поменять на v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3 # <--- ИЗМЕНЕНИЕ

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # У этого экшена последняя версия v3, так что все хорошо

      - name: Build with Gradle
        run: ./gradlew clean build

      # Меняем v4 на v3
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3 # <--- ИЗМЕНЕНИЕ
        with:
          name: bot-jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      # Меняем v4 на v3 - это самый важный шаг, так как именно здесь была ошибка
      - name: Download JAR from build job
        uses: actions/download-artifact@v3 # <--- ГЛАВНОЕ ИЗМЕНЕНИЕ
        with:
          name: bot-jar

      - name: Deploy and restart bot service
        run: |
          JAR_NAME="food_bot_telegram.jar"
          APP_DIR="/home/pi/Desktop/app"

          echo "Deploying new version..."
          # Перемещаем скачанный JAR в папку приложения
          mv $JAR_NAME "$APP_DIR/$JAR_NAME"
          
          echo "Restarting obed-bot service..."
          sudo systemctl restart obed-bot.service
          
          echo "Deployment finished!"