name: Build Docker Image, Deploy on Server

on:
  push:
    branches:
      - main

jobs:
  # --- ЗАДАЧA №1: ПРОВЕРКА И СБОРКА DOCKER-ОБРАЗА В ОБЛАКЕ ---
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.string.outputs.DOCKER_IMAGE_NAME_LC }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 # Изменено с JDK 21 на JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Изменено на '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Apply code formatting with Spotless # Изменено с проверки на применение форматирования
        run: ./gradlew spotlessApply # Изменено с spotlessCheck на spotlessApply

      - name: Convert repository name to lowercase
        id: string
        run: echo "DOCKER_IMAGE_NAME_LC=$(echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.string.outputs.DOCKER_IMAGE_NAME_LC }}:latest

  # --- ЗАДАЧА №2: ДЕПЛОЙ НА RASPBERRY PI ---
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy new version to Docker
        run: |
          IMAGE_NAME="${{ needs.build.outputs.image_name }}:latest"
          CONTAINER_NAME="obed-bot"

          echo "Pulling latest Docker image: $IMAGE_NAME"
          docker pull $IMAGE_NAME

          echo "Stopping and removing old container if it exists..."
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          echo "Starting new container with environment variables and volume..."
          # Запускаем новый контейнер, передавая секреты как переменные окружения и прокидывая волюм
          docker run \
            -d \
            --restart always \
            -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} \
            -e BOT_NAME=${{ secrets.BOT_NAME }} \
            -e BOT_TIME_ZONE="Asia/Yekaterinburg" \
            -v ${{ secrets.EXTERNAL_VOLUME_PATH }}:/app/data  `# Добавлен волюм для сохранения данных` \
            --name $CONTAINER_NAME \
            $IMAGE_NAME
          
          echo "Cleaning up old images..."
          docker image prune -f

          echo "Deployment finished!"
